import type { Issue, Party, Politician, ScoreSnapshot } from "@/types";

export const MOCK_PARTIES: Party[] = [
  { id: "p1", name: "더불어민주당", color: "blue", camp: "blue", created_at: "2024-01-01" },
  { id: "p2", name: "국민의힘",     color: "red",  camp: "red",  created_at: "2024-01-01" },
];

export const MOCK_POLITICIANS: Politician[] = [
  { id: "pol1", name: "이재명", party_id: "p1", position: "대표", region: "인천", profile_image: null, active: true, created_at: "2024-01-01" },
  { id: "pol2", name: "한동훈", party_id: "p2", position: "대표", region: "서울", profile_image: null, active: true, created_at: "2024-01-01" },
  { id: "pol3", name: "박찬대", party_id: "p1", position: "원내대표", region: "부산", profile_image: null, active: true, created_at: "2024-01-01" },
  { id: "pol4", name: "추경호", party_id: "p2", position: "원내대표", region: "대구", profile_image: null, active: true, created_at: "2024-01-01" },
];

export const MOCK_ISSUES: Issue[] = [
  {
    id: "i1",
    title: "A 의원, 뇌물 수수 혐의 기소",
    summary: "검찰이 A 의원을 뇌물 수수 혐의로 불구속 기소했다. 건설업자로부터 5천만원을 수수한 혐의.",
    category: "corruption",
    camp: "red",
    politician_id: null,
    severity: "severe",
    impact_scope: "national",
    source_tier: 1,
    source_url: "https://example.com/news/1",
    source_name: "대한민국 법원",
    raw_score: 9,
    weighted_score: 27,
    ai_analysis: { confidence: 0.95, reasoning: "법원 기소장 기반 사실", category_rationale: "뇌물 수수는 부정부패 카테고리", severity_rationale: "현직 의원 기소는 중대 사안" },
    published_at: "2026-05-18T09:00:00Z",
    created_at: "2026-05-18T10:00:00Z",
    verified: true,
    verification_note: null,
  },
  {
    id: "i2",
    title: "B 전 대표, 허위사실 유포 유죄 판결",
    summary: "법원이 B 전 대표에게 허위사실 유포 혐의로 벌금 500만원을 선고했다.",
    category: "crime",
    camp: "blue",
    politician_id: null,
    severity: "normal",
    impact_scope: "national",
    source_tier: 1,
    source_url: "https://example.com/news/2",
    source_name: "대한민국 법원",
    raw_score: 10,
    weighted_score: 15,
    ai_analysis: { confidence: 0.92, reasoning: "판결문 기반", category_rationale: "유죄 판결은 범죄/사법 카테고리", severity_rationale: "벌금형으로 보통 수준" },
    published_at: "2026-05-15T14:00:00Z",
    created_at: "2026-05-15T15:00:00Z",
    verified: true,
    verification_note: null,
  },
  {
    id: "i3",
    title: "C 의원, 불우이웃 돕기 1억원 기부",
    summary: "C 의원이 개인 재산에서 1억원을 사회복지공동모금회에 기부했다.",
    category: "charity",
    camp: "red",
    politician_id: null,
    severity: "normal",
    impact_scope: "national",
    source_tier: 2,
    source_url: "https://example.com/news/3",
    source_name: "SNU 팩트체크",
    raw_score: 5,
    weighted_score: 7.5,
    ai_analysis: { confidence: 0.98, reasoning: "기부금 영수증 확인", category_rationale: "개인 기부는 선행/봉사", severity_rationale: "1억원 규모는 보통 수준" },
    published_at: "2026-05-17T11:00:00Z",
    created_at: "2026-05-17T12:00:00Z",
    verified: true,
    verification_note: null,
  },
  {
    id: "i4",
    title: "D 의원, 국회 본회의 중 비속어 사용",
    summary: "D 의원이 본회의 토론 중 상대 의원에게 비속어를 사용해 논란이 되고 있다. 국회 속기록에 기록됨.",
    category: "slander",
    camp: "blue",
    politician_id: null,
    severity: "mild",
    impact_scope: "national",
    source_tier: 1,
    source_url: "https://example.com/news/4",
    source_name: "국회 속기록",
    raw_score: 4,
    weighted_score: 4,
    ai_analysis: { confidence: 0.88, reasoning: "속기록 확인", category_rationale: "비속어 사용은 막말/폭언", severity_rationale: "일회성 발언으로 경미" },
    published_at: "2026-05-19T16:00:00Z",
    created_at: "2026-05-19T17:00:00Z",
    verified: true,
    verification_note: null,
  },
  {
    id: "i5",
    title: "E 의원, 청년 주거지원법 단독 발의 통과",
    summary: "E 의원이 발의한 청년 주거지원법이 국회 본회의를 통과했다. 연간 5만 가구 혜택 예상.",
    category: "policy_win",
    camp: "blue",
    politician_id: null,
    severity: "severe",
    impact_scope: "national",
    source_tier: 1,
    source_url: "https://example.com/news/5",
    source_name: "국회 의안정보시스템",
    raw_score: 7,
    weighted_score: 14,
    ai_analysis: { confidence: 0.94, reasoning: "의안정보시스템 확인", category_rationale: "법안 통과는 정책 성공", severity_rationale: "5만 가구 규모로 중대" },
    published_at: "2026-05-16T10:00:00Z",
    created_at: "2026-05-16T11:00:00Z",
    verified: true,
    verification_note: null,
  },
  {
    id: "i6",
    title: "민생지원금 확대안 국회 제출",
    summary: "전 국민 대상 민생지원금 30만원 지급 법안이 국회에 제출되었다. 예산 15조원 규모.",
    category: "controversial",
    camp: "blue",
    politician_id: null,
    severity: "normal",
    impact_scope: "national",
    source_tier: 1,
    source_url: "https://example.com/news/6",
    source_name: "국회 의안정보시스템",
    raw_score: 0,
    weighted_score: 0,
    ai_analysis: { confidence: 0.91, reasoning: "재정 정책으로 찬반 양론", category_rationale: "가치 판단이 갈리는 정책", severity_rationale: "점수 미반영 대상" },
    published_at: "2026-05-14T09:00:00Z",
    created_at: "2026-05-14T10:00:00Z",
    verified: true,
    verification_note: null,
  },
  {
    id: "i7",
    title: "F 의원, 과거 발언과 정반대 입장 표명",
    summary: "F 의원이 3년 전 '절대 반대'했던 법안에 찬성표를 던져 이중잣대 논란.",
    category: "hypocrisy",
    camp: "red",
    politician_id: null,
    severity: "normal",
    impact_scope: "national",
    source_tier: 2,
    source_url: "https://example.com/news/7",
    source_name: "SNU 팩트체크",
    raw_score: 6,
    weighted_score: 9,
    ai_analysis: { confidence: 0.85, reasoning: "과거 발언 영상과 현재 표결 비교", category_rationale: "과거 발언 모순은 위선/이중잣대", severity_rationale: "정책 관련 입장 변경으로 보통" },
    published_at: "2026-05-13T08:00:00Z",
    created_at: "2026-05-13T09:00:00Z",
    verified: true,
    verification_note: null,
  },
  {
    id: "i8",
    title: "G 의원, 선거 공약 3건 중 2건 이행 완료",
    summary: "G 의원이 지난 선거에서 공약한 3건 중 2건을 임기 내 이행했다. 선관위 공약 이행 평가 기준.",
    category: "promise_kept",
    camp: "red",
    politician_id: null,
    severity: "normal",
    impact_scope: "regional",
    source_tier: 1,
    source_url: "https://example.com/news/8",
    source_name: "중앙선거관리위원회",
    raw_score: 6,
    weighted_score: 7.2,
    ai_analysis: { confidence: 0.96, reasoning: "선관위 공약 이행 평가 데이터", category_rationale: "공약 이행 확인", severity_rationale: "2/3 이행으로 보통" },
    published_at: "2026-05-10T10:00:00Z",
    created_at: "2026-05-10T11:00:00Z",
    verified: true,
    verification_note: null,
  },
];

export const MOCK_SNAPSHOT: ScoreSnapshot = {
  id: "snap1",
  date: "2026-05-20",
  blue_negative: 19,
  blue_positive: 14,
  red_negative: 36,
  red_positive: 14.7,
  blue_net: 5,
  red_net: 21.3,
  blue_pct: 19,
  red_pct: 81,
  breakdown: null,
  created_at: "2026-05-20T00:00:00Z",
};
